
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:10.11.21.9}:${eureka.server.port:18761}/eureka/
  instance:
    prefer-ip-address: true #将IP注册到注册中心，当选项为false时，注册到服务中心的信息为主机名

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 2000 #设置触发熔断后，拒绝请求后多长时间开始尝试再次执行。单位为毫秒
        requestVolumeThreshold: 3 #熔断器默认工作时间,默认:5秒.熔断器中断请求5秒后会进入半打开状态,放部分流量过去重试
      execution:
        timeout:
          enabled: true #执行超时机制开启
        isolation:
          strategy: SEMAPHORE #执行隔商策略
          semaphore:
            maxConcurrentRequests: 50 #执行并发请求数
          thread:
            timeoutInMilliseconds: 100000 #线程超时时间

spring:
  output:
    ansi:
      enabled: detect
  main:
    #bannerMode: log
  mvc:
    favicon:
      enabled: false
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: utf-8

  datasource:
    poolName: ${spring.application.name}
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.11.21.14:3306/mdm_admin?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: mdm
    password: Ccpg-test1
    autoCommit: false
    minIdle: 5
    maximumPoolSize: 20
    connectionInitSql: select 1
    hikari:
      idle-timeout: 10000
  data:
    elasticsearch:
      cluster-name: ccpg_es_cluster
      cluster-nodes: 10.11.21.5:9300
      repositories:
        enabled: true

management.security.enabled: false
security:
  basic:
    enabled: false
  oauth2:
    resource:
      loadBalanced: true
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
  sessions: stateless

server:
  port: 8090
  context-path: /
  compression:
    enabled: true

mybatis:
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapperLocations: classpath*:mybatis/*.xml
